
export const loginFormConstants = {
    SET_USERNAME: 'LOGINFORM_SET_USERNAME',
    SET_PASSWORD: 'LOGINFORM_SET_PASSWORD',
    SET_SUBMITTED: 'LOGINFORM_SET_SUBMITTED',
    LOGIN_REQUEST: 'LOGINFORM_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGINFORM_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGINFORM_LOGIN_FAILURE',
    LOGOUT: 'LOGINFORM_LOGOUT'
};
